//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonResources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextConstants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextConstants() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommonResources.TextConstants", typeof(TextConstants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В меню.
        /// </summary>
        public static string MenuFailItemGoHome {
            get {
                return ResourceManager.GetString("MenuFailItemGoHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заново.
        /// </summary>
        public static string MenuFailItemRestart {
            get {
                return ResourceManager.GetString("MenuFailItemRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы проиграли!.
        /// </summary>
        public static string MenuFailTitle {
            get {
                return ResourceManager.GetString("MenuFailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ../../../../CommonResources/Texture/cat.png.
        /// </summary>
        public static string MenuGameImgFilePathCat {
            get {
                return ResourceManager.GetString("MenuGameImgFilePathCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ../../../../CommonResources/Texture/coin.png.
        /// </summary>
        public static string MenuGameImgFilePathTileCoin {
            get {
                return ResourceManager.GetString("MenuGameImgFilePathTileCoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ../../../../CommonResources/Texture/empty.png.
        /// </summary>
        public static string MenuGameImgFilePathTileEmpty {
            get {
                return ResourceManager.GetString("MenuGameImgFilePathTileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ../../../../CommonResources/Texture/end.png.
        /// </summary>
        public static string MenuGameImgFilePathTileEnd {
            get {
                return ResourceManager.GetString("MenuGameImgFilePathTileEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ../../../../CommonResources/Texture/forward.png.
        /// </summary>
        public static string MenuGameImgFilePathTileForward {
            get {
                return ResourceManager.GetString("MenuGameImgFilePathTileForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ../../../../CommonResources/Texture/start.png.
        /// </summary>
        public static string MenuGameImgFilePathTileStart {
            get {
                return ResourceManager.GetString("MenuGameImgFilePathTileStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ../../../../CommonResources/Texture/turnLeft.png.
        /// </summary>
        public static string MenuGameImgFilePathTileTurnLeft {
            get {
                return ResourceManager.GetString("MenuGameImgFilePathTileTurnLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ../../../../CommonResources/Texture/turnRight.png.
        /// </summary>
        public static string MenuGameImgFilePathTileTurnRight {
            get {
                return ResourceManager.GetString("MenuGameImgFilePathTileTurnRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string MenuGameItemScore {
            get {
                return ResourceManager.GetString("MenuGameItemScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string MenuGameTitle {
            get {
                return ResourceManager.GetString("MenuGameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ../../../../CommonResources/Levels.
        /// </summary>
        public static string MenuLevelsFilePath {
            get {
                return ResourceManager.GetString("MenuLevelsFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В меню.
        /// </summary>
        public static string MenuLevelsItemGoHome {
            get {
                return ResourceManager.GetString("MenuLevelsItemGoHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уровень .
        /// </summary>
        public static string MenuLevelsItemLevelName {
            get {
                return ResourceManager.GetString("MenuLevelsItemLevelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уровни.
        /// </summary>
        public static string MenuLevelsTitle {
            get {
                return ResourceManager.GetString("MenuLevelsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выйти.
        /// </summary>
        public static string MenuMainItemExit {
            get {
                return ResourceManager.GetString("MenuMainItemExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Играть.
        /// </summary>
        public static string MenuMainItemPlay {
            get {
                return ResourceManager.GetString("MenuMainItemPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рейтинг.
        /// </summary>
        public static string MenuMainItemRating {
            get {
                return ResourceManager.GetString("MenuMainItemRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Правила.
        /// </summary>
        public static string MenuMainItemRules {
            get {
                return ResourceManager.GetString("MenuMainItemRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Меню.
        /// </summary>
        public static string MenuMainTitle {
            get {
                return ResourceManager.GetString("MenuMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ../../../../CommonResources/Rating.json.
        /// </summary>
        public static string MenuRatingFilePath {
            get {
                return ResourceManager.GetString("MenuRatingFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В меню.
        /// </summary>
        public static string MenuRatingItemGoHome {
            get {
                return ResourceManager.GetString("MenuRatingItemGoHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string MenuRatingItemPlayer {
            get {
                return ResourceManager.GetString("MenuRatingItemPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string MenuRatingItemPlayerScore {
            get {
                return ResourceManager.GetString("MenuRatingItemPlayerScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рейтинг.
        /// </summary>
        public static string MenuRatingTitle {
            get {
                return ResourceManager.GetString("MenuRatingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В меню.
        /// </summary>
        public static string MenuResultItemGoHome {
            get {
                return ResourceManager.GetString("MenuResultItemGoHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать уровень.
        /// </summary>
        public static string MenuResultItemLevel {
            get {
                return ResourceManager.GetString("MenuResultItemLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Следующий уровень.
        /// </summary>
        public static string MenuResultItemNextLevel {
            get {
                return ResourceManager.GetString("MenuResultItemNextLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очки: .
        /// </summary>
        public static string MenuResultItemScore {
            get {
                return ResourceManager.GetString("MenuResultItemScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уровень пройден!.
        /// </summary>
        public static string MenuResultTitle {
            get {
                return ResourceManager.GetString("MenuResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ../../../../CommonResources/Rules.txt.
        /// </summary>
        public static string MenuRulesItemDescriptionFilePath {
            get {
                return ResourceManager.GetString("MenuRulesItemDescriptionFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл описания правил игры не найден.
        /// </summary>
        public static string MenuRulesItemExeption {
            get {
                return ResourceManager.GetString("MenuRulesItemExeption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В меню.
        /// </summary>
        public static string MenuRulesItemGoHome {
            get {
                return ResourceManager.GetString("MenuRulesItemGoHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Правила.
        /// </summary>
        public static string MenuRulesTitle {
            get {
                return ResourceManager.GetString("MenuRulesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите ваш никнейм.
        /// </summary>
        public static string MenuUsernameItemHeading {
            get {
                return ResourceManager.GetString("MenuUsernameItemHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваше имя....
        /// </summary>
        public static string MenuUsernameItemInput {
            get {
                return ResourceManager.GetString("MenuUsernameItemInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        public static string MenuUsernameItemSave {
            get {
                return ResourceManager.GetString("MenuUsernameItemSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tap Tap Dash.
        /// </summary>
        public static string MenuUsernameTitle {
            get {
                return ResourceManager.GetString("MenuUsernameTitle", resourceCulture);
            }
        }
    }
}
